---
benchmark:
- name: Hash#default
  script: hash.default
  prelude: hash = Hash.new { |h,k| h[k] = k.to_i*10}
- name: Hash#default(key)
  script: hash.default(42)
  prelude: hash = Hash.new { |h,k| h[k] = k.to_i*10}
- name: Hash#default=(value)
  script: hash.default = 42
  prelude: hash = { "foo" => 100, "bar" => 300 }
