-
  description: Hash#default
  before: |-
    hash = Hash.new {|h,k| h[k] = k.to_i*10}
  benchmark: |-
    hash.default
-
  description: Hash#default(key)
  before: |-
    hash = Hash.new {|h,k| h[k] = k.to_i*10}
  benchmark: |-
    hash.default(42)
-
  description: Hash#default=(value)
  before: |-
    hash = { "foo" => 100, "bar" => 300 }
  benchmark: |-
    hash.default = 42
