---
benchmark:
- name: Array#product
  script: ary.product
  prelude: ary = [1, 2, 3, 4, 5]
- name: Array#product(other)
  script: ary.product(other)
  prelude: |-
    ary = [1, 2, 3, 4, 5]
    other = [1, 2]
- name: Array#product(other) { |obj| ...}
  script: ary.product(other) { |x| x }
  prelude: |-
    ary = [1, 2, 3, 4, 5]
    other = [1, 2]
